use_frameworks!

platform :ios, '10.0'

target 'TestingCalculator_Example' do
  pod 'TestingCalculator', :path => '../'

  target 'TestingCalculator_Tests' do
    inherit! :search_paths

    
  end
end
